### ISSUE TITLE
Wrong number of smurfs

### ISSUE THREAD

**Issue by HenrikssonErik** [cthit/hubbit#36]
Hi!

I saw that Dev only counted to 12 smurfs in the Hubb while hubbit counted to 27.

**Comment by ViddeM** [comment]
This should now be "resolved" with PR #37 although it was somewhat of a design desition in the way that sessions were calculated. Please keep an eye out for a while tho to confirm this!

Currently I expect this to now be reversed and if anything should show more smurfs in hubbit 2 than in the old hubbit but if you spot cases where this isn't true please open another issue or contact me directly! :)
