### ISSUE TITLE
Last session overflows. Too many lines

### ISSUE THREAD

**Issue by Hoidi** [cthit/hubbit#51]
On My stats page
![image](https://user-images.githubusercontent.com/31310934/156344996-0b112788-7b8f-41a4-8151-0e9b00443a0c.png)

**Comment by ViddeM** [comment]
What device was this on? I can't seem to reproduce the issue
![image](https://user-images.githubusercontent.com/16452604/156605023-739a4211-c4b3-49af-a65f-e8730512a0b1.png)

**Comment by Hoidi** [comment]
"Works on my machine" lol
I'm on my laptop. 1080p screen. Firefox

**Comment by ViddeM** [comment]
"Works on my machine" == is really annoying to debug 😅

**Comment by ViddeM** [comment]
Seems to have been fixed a while back.
