### ISSUE TITLE
As a user, i would like to see HookIT at the bottom of the page so it does not disturb the flow of rest of the commitees

### ISSUE THREAD

**Issue by erikpersson0884** [cthit/hubbit#93]
Currently HookIT is a comitee which can have many members. This results in when there are many HookIT people in Hubben, then hookIT gets very long which puches down the commitees after it which makes the page look wierd. 

By placing hookIT at the end, it would allow it to extend as far down as needed without disturbing the other commitees

![screencapture-hubbit-chalmers-it-2024-01-24-14_55_23](https://github.com/cthit/hubbit/assets/102751768/b0906b41-d4dd-4f07-9700-cf4c654c445f)

**Comment by simon-wg** [comment]
Closed as of #98
